// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/groups": {
    params: {};
  };
  "/dashboard/groups/join": {
    params: {};
  };
  "/dashboard/groups/:groupId": {
    params: {
      "groupId": string;
    };
  };
  "/dashboard/studies/:studyId": {
    params: {
      "studyId": string;
    };
  };
  "/dashboard/studies/:studyId/weeks/:weekNumber": {
    params: {
      "studyId": string;
      "weekNumber": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/dashboard" | "/dashboard/groups" | "/dashboard/groups/join" | "/dashboard/groups/:groupId" | "/dashboard/studies/:studyId" | "/dashboard/studies/:studyId/weeks/:weekNumber";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.groups._index.tsx": {
    id: "routes/dashboard.groups._index";
    page: "/dashboard/groups";
  };
  "routes/dashboard.groups.join.tsx": {
    id: "routes/dashboard.groups.join";
    page: "/dashboard/groups/join";
  };
  "routes/dashboard.groups.$groupId._index.tsx": {
    id: "routes/dashboard.groups.$groupId._index";
    page: "/dashboard/groups/:groupId";
  };
  "routes/dashboard.studies.$studyId._index.tsx": {
    id: "routes/dashboard.studies.$studyId._index";
    page: "/dashboard/studies/:studyId";
  };
  "routes/dashboard.studies.$studyId.weeks.$weekNumber.tsx": {
    id: "routes/dashboard.studies.$studyId.weeks.$weekNumber";
    page: "/dashboard/studies/:studyId/weeks/:weekNumber";
  };
};